name: Deploy to FTP

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 23.4.0  # Use the desired Node.js version

      - name: Install dependencies and build Next.js app
        run: |
          yarn install 
          yarn build 

      - name: Deploy to FTP  
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:  
          server: ${{ secrets.FTP_SERVER }}  
          username: ${{ secrets.FTP_USERNAME }}  
          password: ${{ secrets.FTP_PASSWORD }}  
          port: 21
          protocol: ftp
          local-dir: ./  
          server-dir: /foodieapp.itsamrinaas.my.id/
          timeout: 300000 
